### ISSUE TITLE
Fail to run the train file

### ISSUE THREAD

**Issue by yuehua-Song666** [EPFL-VILAB/XTConsistency#5]
Hi there,
When I run the train file, I got error messages below:

Traceback (most recent call last):
  File "/home/natalie/XTConsistency/train.py", line 147, in <module>
    Fire(main)
  File "/home/natalie/anaconda3/envs/XTConsistency/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/natalie/anaconda3/envs/XTConsistency/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/natalie/anaconda3/envs/XTConsistency/lib/python3.6/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/natalie/XTConsistency/train.py", line 82, in main
    test_set = load_test(energy_loss.get_tasks("test"), buildings=['almena', 'albertville','espanola'])
  File "/home/natalie/XTConsistency/datasets.py", line 101, in load_test
    set3 = list(itertools.islice(test_loader3, 1))[0]
IndexError: list index out of range

Since there has a parameter: buildings=['almena', 'albertville','espanola']
Then I found that after I run: sh ./tools/download_data.sh # Starter data (388MB) I still don't have the dataset file with name of 'espanola'
Can you please tell me where can I find this data or did I do something wrong?
Thanks a lot

**Comment by alexsax** [comment]
I think that you did everything right and a recent commit introduced a small bug. Thanks for looking into this--`espanola` shouldn't be in the demo data. I updated the corresponding files so if you pull and rerun this should now (hopefully) work.

**Comment by yuehua-Song666** [comment]
Thanks a lot! I will try again😁
________________________________

**Comment by alexsax** [comment]
Yes and if it doesn't work then please do reopen this!

**Comment by yuehua-Song666** [comment]
Hi there,

Sorry for disturbing u again and hope u r doing well.
I tired the new code u posted, but I got some new errors:

Traceback (most recent call last):
  File "/home/natalie/anaconda3/envs/XTConsistency/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/natalie/anaconda3/envs/XTConsistency/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/natalie/XTConsistency/train.py", line 147, in <module>
    Fire(main)
  File "/home/natalie/anaconda3/envs/XTConsistency/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/natalie/anaconda3/envs/XTConsistency/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/natalie/anaconda3/envs/XTConsistency/lib/python3.6/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/natalie/XTConsistency/train.py", line 82, in main
    test_set = load_test(energy_loss.get_tasks("test"), buildings=['almena', 'albertville'])
  File "/home/natalie/XTConsistency/datasets.py", line 90, in load_test
    print(f"number of images in {buildings[2]}:")
IndexError: list index out of range

Since in the data.py file line 75, the parameter 'buildings' only has 2 items, so buildings[2] will out of range.
Then I tried to modify it by commenting out lines 90-95 and comment line 98, changing line 99 as test_set = tuple(torch.cat([x,y],dim=0) for x,y in zip(set1, set2))
And I got new issues:

Traceback (most recent call last):
  File "/home/natalie/anaconda3/envs/XTConsistency/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/natalie/anaconda3/envs/XTConsistency/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/natalie/XTConsistency/train.py", line 147, in <module>
    Fire(main)
  File "/home/natalie/anaconda3/envs/XTConsistency/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/natalie/anaconda3/envs/XTConsistency/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/natalie/anaconda3/envs/XTConsistency/lib/python3.6/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/natalie/XTConsistency/train.py", line 83, in main
    ood_set = load_ood(energy_loss.get_tasks("ood"))
  File "/home/natalie/XTConsistency/datasets.py", line 112, in load_ood
    ood_images = list(itertools.islice(ood_loader, 1))[0]
IndexError: list index out of range

I don't know how to figure this out.
I will appreciate it if you would give me some help about this.
Thanks a lot!

Best regards,
Yuehua Song

________________________________

**Comment by alexsax** [comment]
You're totally right. Sorry about that--I didn't notice the scope of the changes. But now I've pushed a new commit and actually tested it this time :) The following should work: `python -m train example_cascade_two_networks --k 1 --fast`.

**Comment by yuehua-Song666** [comment]
Thank you so much for your help, I will try again👍😊

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Sasha Sax <notifications@github.com>
发送时间: Monday, January 25, 2021 6:01:39 PM
收件人: EPFL-VILAB/XTConsistency <XTConsistency@noreply.github.com>
抄送: Yuehua Song <ysong037@uottawa.ca>; Author <author@noreply.github.com>
主题: Re: [EPFL-VILAB/XTConsistency] Fail to run the train file (#5)

Attention : courriel externe | external email

You're totally right. Sorry about that--I didn't notice the scope of the changes. But now I've pushed a new commit and actually tested it this time :) The following should work: python -m train example_cascade_two_networks --k 1 --fast.

**Comment by alexsax** [comment]
Of course! If you try again soon then please pull the latest from the `master` branch. The automatic docker builds usually take some time to complete.

**Comment by yuehua-Song666** [comment]
Thank you for your kindly reminder😊
By the way, you guys did a great work!👍

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Sasha Sax <notifications@github.com>
发送时间: Monday, January 25, 2021 6:06:46 PM
收件人: EPFL-VILAB/XTConsistency <XTConsistency@noreply.github.com>
抄送: Yuehua Song <ysong037@uottawa.ca>; Author <author@noreply.github.com>
主题: Re: [EPFL-VILAB/XTConsistency] Fail to run the train file (#5)

Attention : courriel externe | external email

Of course! If you try again soon then please pull the latest from the master branch. The automatic docker builds usually take some time to complete.

**Comment by alexsax** [comment]
Thanks for the kind words!
